name: Setup
description: Setup repo
runs:
    using: composite
    steps:
        - name: Setup NodeJS
          uses: actions/setup-node@v3

        - name: Cache Deps
          uses: actions/cache@v3
          with:
              path: '**/node_modules'
              key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

        - name: Install Dependencies
          run: yarn install
          shell: bash
