name: Setup
description: Setup repo
inputs:
    registry-url:
        required: false
        default: https://registry.npmjs.org
runs:
    using: composite
    steps:
        - name: Setup NodeJS
          uses: actions/setup-node@v3
          with:
              node-version: '18.x'
              registry-url: ${{ inputs.registry-url }}

        - name: Enable Corepack
          run: corepack enable && yarn -v
          shell: bash

        - name: Get yarn cache directory path
          id: yarn-cache-dir-path
          run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

        - uses: actions/cache@v3
          with:
              path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
              key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
              restore-keys: |
                  ${{ runner.os }}-yarn-

        - name: Install Dependencies
          run: yarn install --immutable --immutable-cache --check-cache
          shell: bash

        - name: Build
          run: yarn build
          shell: bash
