name: Setup
description: Setup repo
inputs:
    registry-url:
        required: false
        default: https://registry.npmjs.org
        description: Registry URL
    node-version:
        required: false
        default: 18.x
        description: Node Version
runs:
    using: composite
    steps:
        - name: Setup NodeJS
          uses: ./.github/actions/setup-node
          with:
              registry-url: ${{ inputs.registry-url }}
              node-version: ${{ inputs.node-version }}

        - name: Install Dependencies
          run: yarn install --immutable --immutable-cache
          shell: bash

        - name: Build
          run: yarn build
          shell: bash
