name: Setup
description: Setup repo
inputs:
    registry-url:
        required: false
        default: https://registry.npmjs.org
runs:
    using: composite
    steps:
        - name: Setup NodeJS
          uses: actions/setup-node@v3
          with:
              node-version: '18.x'
              registry-url: ${{ inputs.registry-url }}
              cache: 'yarn'

        - name: Install Dependencies
          run: yarn install --immutable --immutable-cache --check-cache
          shell: bash

        - name: Build
          run: yarn build
          shell: bash
