name: Publish
description: Publishes a package to NPM and GPR

inputs:
    package:
        description: Package to publish. Must be a directory in /packages
        required: true

runs:
    using: composite
    steps:
        - uses: actions/checkout@v3
        - id: get-packages
          uses: ./.github/actions/get-packages

        - id: check-input
          shell: cmd
          run: |
              VALID=${{ contains(fromJSON(steps.get-packages.outputs.packages), inputs.package) }}
              echo "::set-output name=valid::{VALID}"

        - name: Publish ${{ inputs.package }} to NPM
          if: ${{ steps.check-input.outputs.valid }}
          uses: JS-DevTools/npm-publish@v1
          with:
              token: ${{ secrets.NPM_TOKEN }}
              package: ./packages/${{ inputs.package }}/package.json
              access: public
              registry: https://registry.npmjs.org

        - name: Publish ${{ inputs.package }} to GPR
          if: ${{ steps.check-input.outputs.valid }}
          uses: JS-DevTools/npm-publish@v1
          with:
              token: ${{ secrets.NPM_TOKEN }}
              package: ./packages/${{ inputs.package }}/package.json
              access: public
              registry: https://npm.pkg.github.com
