name: CI

on:
    push:
        branches:
            - main
    workflow_run:
        workflows: ['Publish']
        types:
            - requested

jobs:
    setup:
        uses: ./.github/workflows/setup.yaml

    test:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: yarn test

    lint:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: Lint
              run: yarn lint
