name: CI

on:
    - push
    - workflow_dispatch
    - workflow_call

jobs:
    install:
        name: Setup Environment
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-node
            - run: yarn build
            - run: yarn install --immutable --immutable-cache --check-cache

    lint:
        name: Lint
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
            - run: yarn lint

    typecheck:
        name: Typecheck
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
            - run: yarn typecheck

    build:
        name: Test
        needs: [install]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [14.x, 16.x, 18.x]
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn test
