name: CI

on:
    push:
        branches:
            - main
    workflow_run:
        workflows: ['Publish']
        types:
            - requested

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Build
              run: yarn build

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Test
              run: yarn test

    lint:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Lint
              run: yarn lint
