name: CI

on:
    push:
        branches:
            - main
    workflow_run:
        workflows: ['Publish']
        types:
            - requested

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup
              run: actions/setup@main

            - name: Build
              run: yarn build

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Setup
              run: actions/setup@main

            - name: Test
              run: yarn test

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Setup
              run: actions/setup@main

            - name: Lint
              run: yarn lint
