name: CI

on:
    - push
    - workflow_dispatch

jobs:
    install:
        name: Get Packages
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.get-packages.outputs.packages }}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup-node
            - run: yarn install --immutable --immutable-cache
            - id: get-packages
              shell: python
              run: |
                  import os, json
                  packages=os.listdir('packages')
                  jsonPackages=json.dumps(packages)
                  print(f'::set-output name=packages::{jsonPackages}')
                  os.system('echo "## Packages Loaded" >> $GITHUB_STEP_SUMMARY')
                  os.system('echo "" >> $GITHUB_STEP_SUMMARY')
                  for package in packages:
                      os.system(f'echo "- {package}" >> $GITHUB_STEP_SUMMARY')

    lint:
        name: Lint
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
            - run: yarn lint

    test:
        name: Test
        needs: [install]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [14.x, 16.x, 18.x]
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn test

    typecheck:
        name: Typecheck
        needs: [install]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
            - run: yarn typecheck

    build:
        name: Build
        needs: [install]
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                node-version: [14.x, 16.x, 18.x]
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
              with:
                  node-version: ${{ matrix.node-version }}
            - run: yarn build
