name: CI

on:
    - push
    - workflow_dispatch

jobs:
    get-packages:
        name: Get Packages
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.get-packages.outputs.packages }}
        steps:
            - uses: actions/checkout@v3
            - id: get-packages
              uses: ./.github/actions/get-packages

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup
              uses: ./.github/actions/setup
            - name: Lint
              run: yarn lint

    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup
              uses: ./.github/actions/setup
            - name: Test
              run: yarn test

    tag:
        name: Tag
        needs: [lint, test, get-packages]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJSON(needs.get-packages.outputs.packages) }}
        outputs:
            publish: ${{ steps.status.outputs.publish }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - name: Tag commit if version has changed
              id: tag
              uses: salsify/action-detect-and-tag-new-version@v2
              with:
                  tag-template: ${{ matrix.package }}/v{{VERSION}}
                  version-command: jq '.version' ./packages/${{ matrix.package }}/package.json
            - id: status
              run: echo "::set-output name=publish::${{ steps.tag.output.tag != '' }}"

    publish-npm:
        name: Publish to NPM
        needs: [get-packages, test, tag]
        if: ${{ needs.tag.outputs.publish }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJSON(needs.get-packages.outputs.packages) }}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
              with:
                  registry-url: https://registry.npmjs.org
            - run: yarn workspace @wiggindev/${{ matrix.package }} npm publish --access public --tolerate-republish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    publish-gpr:
        name: Publish to GPR
        needs: [get-packages, test, tag]
        if: ${{ needs.tag.outputs.publish }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: ${{ fromJSON(needs.get-packages.outputs.packages) }}
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/setup
              with:
                  registry-url: https://npm.pkg.github.com
            - run: yarn workspace @wiggindev/${{ matrix.package }} npm publish --access public --tolerate-republish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
              shell: bash
