name: Publish

on: workflow_dispatch

jobs:
    get-packages:
        name: Get Packages
        runs-on: ubuntu-latest
        outputs:
            packages: ${{ steps.get-packages.outputs.packages }}
        steps:
            - uses: actions/checkout@v3
            - id: get-packages
              uses: ./.github/actions/get-packages

    ci:
        name: CI
        uses: ./.github/workflows/ci.yaml

    publish:
        name: Publish to NPM
        needs: [get-packages, ci]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                package: ${{ fromJSON(needs.get-packages.outputs.packages) }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Publish ${{ matrix.package }}
              id: publish
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./packages/${{ matrix.package }}/package.json
                  access: public

            - name: Check status
              run: |
                  echo "${{ matrix.package }} version: ${{ steps.publish.outputs.version }}"
