name: Publish

on: workflow_dispatch

jobs:
    ci:
        name: CI
        uses: ./.github/workflows/ci.yaml

    publish:
        name: Publish
        needs: ci
        runs-on: ubuntu-latest

        strategy:
            matrix:
                package:
                    - utils
                    - hooks
                registry:
                    - npm
                    - gpr
                include:
                    - registry: npm
                      url: https://registry.npmjs.org
                      token: ${{ secrets.NPM_TOKEN }}
                    - registry: gpr
                    - url: https://npm.pkg.github.com
                      token: ${{ github.token }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Publish ${{ matrix.package }} to ${{ matrix.registry }}
              id: publish
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ matrix.token }}
                  package: ./packages/${{ matrix.package }}/package.json
                  access: public
                  registry: ${{ matrix.url }}

            - name: Check status
              run: |
                  echo "${{ matrix.package }} version on ${{ matrix.registry }}: ${{ steps.publish.outputs.version }}"
