name: Publish

on: workflow_dispatch

jobs:
    ci:
        name: CI
        uses: ./.github/workflows/ci.yaml

    publish:
        name: Publish to NPM
        needs: ci
        runs-on: ubuntu-latest

        strategy:
            matrix:
                package:
                    - utils
                    - hooks
                registry:
                    - https://registry.npmjs.org
                    - https://npm.pkg.github.com
                include:
                    - registry: https://registry.npmjs.org
                      token: ${{ secrets.NPM_TOKEN }}
                    - registry: https://npm.pkg.github.com
                      token: ${{ github.token }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Publish ${{ matrix.package }} to ${{ matrix.registry }}
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ matrix.token }}
                  package: ./packages/${{ matrix.package }}/package.json
                  access: public
                  registry: ${{ matrix.registry }}
