name: Publish

on: workflow_dispatch

jobs:
    ci:
        name: CI
        uses: ./.github/workflows/ci.yaml

    publish:
        name: Publish to NPM
        needs: ci
        runs-on: ubuntu-latest

        strategy:
            matrix:
                package:
                    - utils
                    - hooks
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup
              uses: ./.github/actions/setup

            - name: Publish ${{ matrix.package }}
              id: publish
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./packages/${{ matrix.package }}/package.json
                  access: public

            - name: Check status
              run: |
                  echo "${{ matrix.package }} version: ${{ steps.publish.outputs.version }}"
