name: Publish

on: workflow_dispatch

jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: ./setup.yaml

    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: ./ci.yaml

    publish:
        needs: [setup, ci]
        runs-on: ubuntu-latest
        steps:
            - name: Publish utils
              id: publish-utils
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./packages/utils/package.json
                  access: public

            - name: Publish hooks
              id: publish-hooks
              uses: JS-DevTools/npm-publish@v1
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  package: ./packages/hooks/package.json
                  access: public
