name: Lint

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup NodeJS (with NPM Registry)
              uses: actions/setup-node@v3
              with:
                  registry-url: 'https://registry.npmjs.org'

            - name: Install Dependencies
            - run: yarn install --frozen-lockfile

            - name: Publish to NPM
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

            - name: Setup NodeJS (with GH Registry)
            - uses: actions/setup-node@v3
              with:
                  registry-url: 'https://npm.pkg.github.com'

            - name: Publish to GHR
            - run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
